name: API Controller Build and Upload Coverage Data

on:
  schedule:
    - cron:  '0 20 * * *'
  workflow_dispatch:
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run hostname
        run: hostname
      - name: Fix host entry
        run: sudo echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts
      - name: Show hosts
        run: cat /etc/hosts
   
      - name: Install dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev
      
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: ^1.14
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: |
          cd import-export-cli
          go vet ./...
          ./build.sh -t apictl.go -v 4.3.0

      - name: Start APIM
        run: |
          cd import-export-cli/integration/ci-resources
          ./start-apim.sh
        shell: bash

      - name: Test
        run: |
          cd import-export-cli/integration
          go test -p 1 -timeout 0 -archive apictl-4.3.0-linux-x64.tar.gz -race -coverprofile=coverage.txt -covermode=atomic ./pkg/...
      
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          flags: unit_tests
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: nandika/apim-apps
